export const DEFAULT_WORDS_PER_CAPTION = 4;
export const DEFAULT_MAX_TOKENS_PER_CAPTION = DEFAULT_WORDS_PER_CAPTION;
export const DEFAULT_SPLIT_CAPTIONS_ON_PUNCTUATION = true;
export const MIN_CAPTION_DURATION_SECONDS = 0.8;
